name: nyt-connections-rag
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - jupyterlab
  - nltk
  - ipywidgets
  - faiss-cpu
  - pip
  - pip:
      - python-dotenv
      - openai
      - sentence-transformers
